//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Plugins {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.Plugins.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InstalledPluginsPageView_Uninstalled {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Uninstalled", resourceCulture);
            }
        }
        
        public static string InstalledPluginsInfoDataTemplate_LoadingError_Text {
            get {
                return ResourceManager.GetString("InstalledPluginsInfoDataTemplate_LoadingError_Text", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Uninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Uninstall", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_UninstalledMessageTitle {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_UninstalledMessageTitle", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_UninstalledMessage {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_UninstalledMessage", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_CancelUninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_CancelUninstall", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_Description {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_Description", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_AdditionalInfo {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo", resourceCulture);
            }
        }
        
        public static string PluginsMarketPageView_ToggleSwitch_OnlyVerified {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_ToggleSwitch_OnlyVerified", resourceCulture);
            }
        }
        
        public static string PluginsMarketPageView_InfoBar_IsVerified_Message {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_InfoBar_IsVerified_Message", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        public static string PluginsMarketPageView_Install {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_Install", resourceCulture);
            }
        }
        
        public static string PluginsMarketPageView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Dependencies {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Dependencies", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_AllVersions {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_AllVersions", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Author {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Author", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_DownloadCount {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_DownloadCount", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Tags {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Tags", resourceCulture);
            }
        }
        
        public static string SourceDialogViewModel_NameValidation_NameIsRequired {
            get {
                return ResourceManager.GetString("SourceDialogViewModel_NameValidation_NameIsRequired", resourceCulture);
            }
        }
        
        public static string SourceDialogViewModel_SourceUriValidation_SourceUriIsRequired {
            get {
                return ResourceManager.GetString("SourceDialogViewModel_SourceUriValidation_SourceUriIsRequired", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesViewModel_AddDialog_Title {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_AddDialog_Title", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesViewModel_AddDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_AddDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string PluginsSourceViewModel_EditDialog_Title {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_EditDialog_Title", resourceCulture);
            }
        }
        
        public static string PluginsSourceViewModel_EditDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_EditDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string SourcesDialogView_Name {
            get {
                return ResourceManager.GetString("SourcesDialogView_Name", resourceCulture);
            }
        }
        
        public static string SourcesDialogView_URL {
            get {
                return ResourceManager.GetString("SourcesDialogView_URL", resourceCulture);
            }
        }
        
        public static string SourcesDialogView_Username {
            get {
                return ResourceManager.GetString("SourcesDialogView_Username", resourceCulture);
            }
        }
        
        public static string SourcesDialogView_Password {
            get {
                return ResourceManager.GetString("SourcesDialogView_Password", resourceCulture);
            }
        }
        
        public static string OpenInstalledPluginsCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Title", resourceCulture);
            }
        }
        
        public static string OpenInstalledPluginsCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Description", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_Name", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Source {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Source", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Version {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Version", resourceCulture);
            }
        }
        
        public static string OpenPluginsMarketCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenPluginsMarketCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageViewModel_Title {
            get {
                return ResourceManager.GetString("InstalledPluginsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageViewModel_IntallManuallyDialog_Title {
            get {
                return ResourceManager.GetString("InstalledPluginsPageViewModel_IntallManuallyDialog_Title", resourceCulture);
            }
        }
        
        public static string OpenInstalledPluginsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenInstalledPluginsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string InstalledPluginsPageView_InfoBarLoadingError_Title {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_InfoBarLoadingError_Title", resourceCulture);
            }
        }
        
        public static string PluginsMarketPageViewModel_Title {
            get {
                return ResourceManager.GetString("PluginsMarketPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenPluginsMarketCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_Action_Title", resourceCulture);
            }
        }
        
        public static string OpenPluginsMarketCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_Action_Description", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesViewModel_MenuItem_Add_Title {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_MenuItem_Add_Title", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesView_NameColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_NameColumn_Header", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesView_UriColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_UriColumn_Header", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesView_EditColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_EditColumn_Header", resourceCulture);
            }
        }
        
        public static string SettingsPluginsSourcesView_DeleteColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_DeleteColumn_Header", resourceCulture);
            }
        }
        
        public static string PluginsSourceViewModel_RemoveDialog_Title {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_RemoveDialog_Title", resourceCulture);
            }
        }
        
        public static string PluginsSourceViewModel_RemoveDialog_Message {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_RemoveDialog_Message", resourceCulture);
            }
        }
        
        public static string AddPluginsSourceCommand_CommandInfo_Title {
            get {
                return ResourceManager.GetString("AddPluginsSourceCommand_CommandInfo_Title", resourceCulture);
            }
        }
        
        public static string AddPluginsSourceCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("AddPluginsSourceCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string EditPluginsSourceCommand_CommandInfo_Title {
            get {
                return ResourceManager.GetString("EditPluginsSourceCommand_CommandInfo_Title", resourceCulture);
            }
        }
        
        public static string EditPluginsSourceCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("EditPluginsSourceCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string DeletePluginsSourceCommand_CommandInfo_Title {
            get {
                return ResourceManager.GetString("DeletePluginsSourceCommand_CommandInfo_Title", resourceCulture);
            }
        }
        
        public static string DeletePluginsSourceCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("DeletePluginsSourceCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string PluginInfoViewModel_InstallCommand_Title {
            get {
                return ResourceManager.GetString("PluginInfoViewModel_InstallCommand_Title", resourceCulture);
            }
        }
        
        public static string PluginSettingsTreePageMenu_Name {
            get {
                return ResourceManager.GetString("PluginSettingsTreePageMenu_Name", resourceCulture);
            }
        }
    }
}
