//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Plugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.Plugins.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command adds source for plugins.
        /// </summary>
        public static string AddPluginsSourceCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("AddPluginsSourceCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add plugins&apos; source.
        /// </summary>
        public static string AddPluginsSourceCommand_CommandInfo_Title {
            get {
                return ResourceManager.GetString("AddPluginsSourceCommand_CommandInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command deletes source for plugins.
        /// </summary>
        public static string DeletePluginsSourceCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("DeletePluginsSourceCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete plugins&apos; source.
        /// </summary>
        public static string DeletePluginsSourceCommand_CommandInfo_Title {
            get {
                return ResourceManager.GetString("DeletePluginsSourceCommand_CommandInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command edits source for plugins.
        /// </summary>
        public static string EditPluginsSourceCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("EditPluginsSourceCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit plugins&apos; source.
        /// </summary>
        public static string EditPluginsSourceCommand_CommandInfo_Title {
            get {
                return ResourceManager.GetString("EditPluginsSourceCommand_CommandInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading error.
        /// </summary>
        public static string InstalledPluginsInfoDataTemplate_LoadingError_Text {
            get {
                return ResourceManager.GetString("InstalledPluginsInfoDataTemplate_LoadingError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All versions.
        /// </summary>
        public static string InstalledPluginsPageView_AllVersions {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_AllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string InstalledPluginsPageView_CancelUninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_CancelUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Error.
        /// </summary>
        public static string InstalledPluginsPageView_InfoBarLoadingError_Title {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_InfoBarLoadingError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select plugin.
        /// </summary>
        public static string InstalledPluginsPageView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string InstalledPluginsPageView_Tab_AdditionalInfo {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Author {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies: .
        /// </summary>
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Dependencies {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads: .
        /// </summary>
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_DownloadCount {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_DownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: .
        /// </summary>
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Source {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags: .
        /// </summary>
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Tags {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string InstalledPluginsPageView_Tab_AdditionalInfo_Version {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_AdditionalInfo_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InstalledPluginsPageView_Tab_Description {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Tab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string InstalledPluginsPageView_Uninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        public static string InstalledPluginsPageView_Uninstalled {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_Uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin has been marked for deletion. It will be removed on the next application load..
        /// </summary>
        public static string InstalledPluginsPageView_UninstalledMessage {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_UninstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        public static string InstalledPluginsPageView_UninstalledMessageTitle {
            get {
                return ResourceManager.GetString("InstalledPluginsPageView_UninstalledMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select plugin to install.
        /// </summary>
        public static string InstalledPluginsPageViewModel_IntallManuallyDialog_Title {
            get {
                return ResourceManager.GetString("InstalledPluginsPageViewModel_IntallManuallyDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Plugins.
        /// </summary>
        public static string InstalledPluginsPageViewModel_Title {
            get {
                return ResourceManager.GetString("InstalledPluginsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Installed Plugins.
        /// </summary>
        public static string OpenInstalledPluginsCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Plugins.
        /// </summary>
        public static string OpenInstalledPluginsCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command opens intalled plugins page.
        /// </summary>
        public static string OpenInstalledPluginsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Installed Plugins.
        /// </summary>
        public static string OpenInstalledPluginsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open plugins market page.
        /// </summary>
        public static string OpenPluginsMarketCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Market.
        /// </summary>
        public static string OpenPluginsMarketCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command opens plugins market page.
        /// </summary>
        public static string OpenPluginsMarketCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Plugins Market.
        /// </summary>
        public static string OpenPluginsMarketCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenPluginsMarketCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string PluginInfoViewModel_InstallCommand_Title {
            get {
                return ResourceManager.GetString("PluginInfoViewModel_InstallCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is verified by developers.
        /// </summary>
        public static string PluginsMarketPageView_InfoBar_IsVerified_Message {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_InfoBar_IsVerified_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PluginsMarketPageView_Install {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select plugin.
        /// </summary>
        public static string PluginsMarketPageView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only verified.
        /// </summary>
        public static string PluginsMarketPageView_ToggleSwitch_OnlyVerified {
            get {
                return ResourceManager.GetString("PluginsMarketPageView_ToggleSwitch_OnlyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Market.
        /// </summary>
        public static string PluginsMarketPageViewModel_Title {
            get {
                return ResourceManager.GetString("PluginsMarketPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PluginsSourceViewModel_EditDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_EditDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit plugin source.
        /// </summary>
        public static string PluginsSourceViewModel_EditDialog_Title {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_EditDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this source?.
        /// </summary>
        public static string PluginsSourceViewModel_RemoveDialog_Message {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_RemoveDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Source.
        /// </summary>
        public static string PluginsSourceViewModel_RemoveDialog_Title {
            get {
                return ResourceManager.GetString("PluginsSourceViewModel_RemoveDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SettingsPluginsSourcesView_DeleteColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_DeleteColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SettingsPluginsSourcesView_EditColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_EditColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsPluginsSourcesView_NameColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_NameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        public static string SettingsPluginsSourcesView_UriColumn_Header {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesView_UriColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SettingsPluginsSourcesViewModel_AddDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_AddDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new plugin source.
        /// </summary>
        public static string SettingsPluginsSourcesViewModel_AddDialog_Title {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_AddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Source.
        /// </summary>
        public static string SettingsPluginsSourcesViewModel_MenuItem_Add_Title {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_MenuItem_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Sources.
        /// </summary>
        public static string SettingsPluginsSourcesViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsPluginsSourcesViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string SourceDialogViewModel_NameValidation_NameIsRequired {
            get {
                return ResourceManager.GetString("SourceDialogViewModel_NameValidation_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URI is required.
        /// </summary>
        public static string SourceDialogViewModel_SourceUriValidation_SourceUriIsRequired {
            get {
                return ResourceManager.GetString("SourceDialogViewModel_SourceUriValidation_SourceUriIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SourcesDialogView_Name {
            get {
                return ResourceManager.GetString("SourcesDialogView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string SourcesDialogView_Password {
            get {
                return ResourceManager.GetString("SourcesDialogView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Address.
        /// </summary>
        public static string SourcesDialogView_URL {
            get {
                return ResourceManager.GetString("SourcesDialogView_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SourcesDialogView_Username {
            get {
                return ResourceManager.GetString("SourcesDialogView_Username", resourceCulture);
            }
        }
    }
}
