//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.GeoMap {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.GeoMap.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GeoPointDialogViewModel_Step {
            get {
                return ResourceManager.GetString("GeoPointDialogViewModel_Step", resourceCulture);
            }
        }
        
        public static string GeoPointDialogPrefab_Content_Title {
            get {
                return ResourceManager.GetString("GeoPointDialogPrefab_Content_Title", resourceCulture);
            }
        }
        
        public static string GeoPointDialogViewModel_Anchor_Title {
            get {
                return ResourceManager.GetString("GeoPointDialogViewModel_Anchor_Title", resourceCulture);
            }
        }
        
        public static string MapModeProperty_MapModeInfo_Offline {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Offline", resourceCulture);
            }
        }
        
        public static string MapModeProperty_MapModeInfo_Online {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Online", resourceCulture);
            }
        }
        
        public static string MapModeProperty_MapModeInfo_Mixed {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Mixed", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_ModeProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_ModeProperty_Title", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_TileProviderProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_TileProviderProperty_Title", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsGeoMapViewModel_Name", resourceCulture);
            }
        }
        
        public static string ChangeTileProviderCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeTileProviderCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeTileProviderCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeTileProviderCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ChangeMinZoomCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeMinZoomCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ChangeMaxZoomCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeMaxZoomCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ChangeMinZoomCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeMinZoomCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeMaxZoomCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeMaxZoomCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_CommonSection_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_CommonSection_Title", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_ZoomSection_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_ZoomSection_Title", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_MinZoomProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MinZoomProperty_Title", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_MaxZoomProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MaxZoomProperty_Title", resourceCulture);
            }
        }
        
        public static string EditApiKeyDialogView_ApiKeyProperty_Title {
            get {
                return ResourceManager.GetString("EditApiKeyDialogView_ApiKeyProperty_Title", resourceCulture);
            }
        }
        
        public static string TileProviderGroup_Other_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Other_Name", resourceCulture);
            }
        }
        
        public static string TileProviderGroup_Yandex_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Yandex_Name", resourceCulture);
            }
        }
        
        public static string TileProviderGroup_Bing_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Bing_Name", resourceCulture);
            }
        }
        
        public static string BingTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("BingTileProvider_Info_Name", resourceCulture);
            }
        }
        
        public static string YandexTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("YandexTileProvider_Info_Name", resourceCulture);
            }
        }
        
        public static string EmptyTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("EmptyTileProvider_Info_Name", resourceCulture);
            }
        }
        
        public static string EditApiKeyDialogPrefab_Content_Title {
            get {
                return ResourceManager.GetString("EditApiKeyDialogPrefab_Content_Title", resourceCulture);
            }
        }
        
        public static string EditApiKeyDialogPrefab_Content_PrimaryButton {
            get {
                return ResourceManager.GetString("EditApiKeyDialogPrefab_Content_PrimaryButton", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_SetCurrentProvider_Tooltip {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_SetCurrentProvider_Tooltip", resourceCulture);
            }
        }
        
        public static string SettingsGeoMapView_EditProviderApiKey_Tooltip {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_EditProviderApiKey_Tooltip", resourceCulture);
            }
        }
    }
}
