//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.GeoMap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.GeoMap.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Imagery.
        /// </summary>
        public static string ArcGisWorldImageryTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ArcGisWorldImageryTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Physical.
        /// </summary>
        public static string ArcGisWorldPhysicalTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ArcGisWorldPhysicalTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaded Relief.
        /// </summary>
        public static string ArcGisWorldShadedReliefTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ArcGisWorldShadedReliefTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Street.
        /// </summary>
        public static string ArcGisWorldStreetTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ArcGisWorldStreetTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Terrain.
        /// </summary>
        public static string ArcGisWorldTerrainTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ArcGisWorldTerrainTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Topo.
        /// </summary>
        public static string ArcGisWorldTopoTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ArcGisWorldTopoTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string BingHybridTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("BingHybridTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        public static string BingRoadTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("BingRoadTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string BingSatelliteTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("BingSatelliteTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that changes maximum zoom level.
        /// </summary>
        public static string ChangeMaxZoomCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeMaxZoomCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change max zoom.
        /// </summary>
        public static string ChangeMaxZoomCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeMaxZoomCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that changes minimum zoom level.
        /// </summary>
        public static string ChangeMinZoomCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeMinZoomCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change min zoom.
        /// </summary>
        public static string ChangeMinZoomCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeMinZoomCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that changes map tile provider.
        /// </summary>
        public static string ChangeTileProviderCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeTileProviderCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tile provider.
        /// </summary>
        public static string ChangeTileProviderCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeTileProviderCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string CyclOsmTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("CyclOsmTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditApiKeyDialogPrefab_Content_PrimaryButton {
            get {
                return ResourceManager.GetString("EditApiKeyDialogPrefab_Content_PrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit API Key.
        /// </summary>
        public static string EditApiKeyDialogPrefab_Content_Title {
            get {
                return ResourceManager.GetString("EditApiKeyDialogPrefab_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map provider API Key.
        /// </summary>
        public static string EditApiKeyDialogView_ApiKeyProperty_Title {
            get {
                return ResourceManager.GetString("EditApiKeyDialogView_ApiKeyProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string EmptyTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("EmptyTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Coordinates.
        /// </summary>
        public static string GeoPointDialogPrefab_Content_Title {
            get {
                return ResourceManager.GetString("GeoPointDialogPrefab_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string GeoPointDialogViewModel_Anchor_Title {
            get {
                return ResourceManager.GetString("GeoPointDialogViewModel_Anchor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string GeoPointDialogViewModel_Step {
            get {
                return ResourceManager.GetString("GeoPointDialogViewModel_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string GoogleHybridTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("GoogleHybridTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string GoogleMapTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("GoogleMapTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string GoogleSatelliteTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("GoogleSatelliteTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string GoogleTerrainTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("GoogleTerrainTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string HereHybridTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("HereHybridTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string HereMapTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("HereMapTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string HereSatelliteTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("HereSatelliteTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string HereTerrainTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("HereTerrainTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanitarian.
        /// </summary>
        public static string HotOsmTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("HotOsmTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to map provider &apos;{0}&apos;. Check your internet connection..
        /// </summary>
        public static string HttpTileProvider_Error_NetworkError_Message {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_NetworkError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        public static string HttpTileProvider_Error_NetworkError_Title {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_NetworkError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map provider &apos;{0}&apos; is temporarily unavailable. Retrying automatically..
        /// </summary>
        public static string HttpTileProvider_Error_ServerError_Message {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_ServerError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string HttpTileProvider_Error_ServerError_Title {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_ServerError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map provider &apos;{0}&apos; is not responding. Retrying automatically..
        /// </summary>
        public static string HttpTileProvider_Error_Timeout_Message {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_Timeout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout.
        /// </summary>
        public static string HttpTileProvider_Error_Timeout_Title {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_Timeout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing API key for map provider &apos;{0}&apos;. Please set a valid API key in Settings..
        /// </summary>
        public static string HttpTileProvider_Error_Unauthorized_Message {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_Unauthorized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization error.
        /// </summary>
        public static string HttpTileProvider_Error_Unauthorized_Title {
            get {
                return ResourceManager.GetString("HttpTileProvider_Error_Unauthorized_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string MapModeProperty_MapModeInfo_Mixed {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use cached tiles first and load missing tiles online..
        /// </summary>
        public static string MapModeProperty_MapModeInfo_Mixed_Description {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Mixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string MapModeProperty_MapModeInfo_Offline {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only locally cached map tiles..
        /// </summary>
        public static string MapModeProperty_MapModeInfo_Offline_Description {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Offline_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string MapModeProperty_MapModeInfo_Online {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load map tiles from the selected online provider..
        /// </summary>
        public static string MapModeProperty_MapModeInfo_Online_Description {
            get {
                return ResourceManager.GetString("MapModeProperty_MapModeInfo_Online_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ruler end point.
        /// </summary>
        public static string MapRuler_PickEnd {
            get {
                return ResourceManager.GetString("MapRuler_PickEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the ruler start point.
        /// </summary>
        public static string MapRuler_PickStart {
            get {
                return ResourceManager.GetString("MapRuler_PickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruler.
        /// </summary>
        public static string MapRuler_Tooltip {
            get {
                return ResourceManager.GetString("MapRuler_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map loading.
        /// </summary>
        public static string MapStatusView_Details_Title {
            get {
                return ResourceManager.GetString("MapStatusView_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map settings.
        /// </summary>
        public static string MapStatusView_NavigationButton_Settings {
            get {
                return ResourceManager.GetString("MapStatusView_NavigationButton_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active requests.
        /// </summary>
        public static string MapStatusView_Row_ActiveRequests {
            get {
                return ResourceManager.GetString("MapStatusView_Row_ActiveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        public static string MapStatusView_Row_CacheHits {
            get {
                return ResourceManager.GetString("MapStatusView_Row_CacheHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misses.
        /// </summary>
        public static string MapStatusView_Row_CacheMisses {
            get {
                return ResourceManager.GetString("MapStatusView_Row_CacheMisses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string MapStatusView_Row_CacheTiles {
            get {
                return ResourceManager.GetString("MapStatusView_Row_CacheTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded size.
        /// </summary>
        public static string MapStatusView_Row_DownloadedSize {
            get {
                return ResourceManager.GetString("MapStatusView_Row_DownloadedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded tiles.
        /// </summary>
        public static string MapStatusView_Row_DownloadedTiles {
            get {
                return ResourceManager.GetString("MapStatusView_Row_DownloadedTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed downloads.
        /// </summary>
        public static string MapStatusView_Row_FailedDownloads {
            get {
                return ResourceManager.GetString("MapStatusView_Row_FailedDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder capacity.
        /// </summary>
        public static string MapStatusView_Row_FileCacheCapacity {
            get {
                return ResourceManager.GetString("MapStatusView_Row_FileCacheCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder size.
        /// </summary>
        public static string MapStatusView_Row_FolderSize {
            get {
                return ResourceManager.GetString("MapStatusView_Row_FolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string MapStatusView_Row_MapMode {
            get {
                return ResourceManager.GetString("MapStatusView_Row_MapMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache size.
        /// </summary>
        public static string MapStatusView_Row_MemoryCacheSize {
            get {
                return ResourceManager.GetString("MapStatusView_Row_MemoryCacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network rate.
        /// </summary>
        public static string MapStatusView_Row_NetworkRate {
            get {
                return ResourceManager.GetString("MapStatusView_Row_NetworkRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network requests.
        /// </summary>
        public static string MapStatusView_Row_NetworkRequests {
            get {
                return ResourceManager.GetString("MapStatusView_Row_NetworkRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel downloads.
        /// </summary>
        public static string MapStatusView_Row_ParallelDownloads {
            get {
                return ResourceManager.GetString("MapStatusView_Row_ParallelDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string MapStatusView_Row_Queue {
            get {
                return ResourceManager.GetString("MapStatusView_Row_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued requests.
        /// </summary>
        public static string MapStatusView_Row_QueuedRequestsTotal {
            get {
                return ResourceManager.GetString("MapStatusView_Row_QueuedRequestsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile requests.
        /// </summary>
        public static string MapStatusView_Row_TotalRequests {
            get {
                return ResourceManager.GetString("MapStatusView_Row_TotalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map folder.
        /// </summary>
        public static string MapStatusView_Section_FileCache {
            get {
                return ResourceManager.GetString("MapStatusView_Section_FileCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader.
        /// </summary>
        public static string MapStatusView_Section_Loader {
            get {
                return ResourceManager.GetString("MapStatusView_Section_Loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory cache.
        /// </summary>
        public static string MapStatusView_Section_MemoryCache {
            get {
                return ResourceManager.GetString("MapStatusView_Section_MemoryCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom level {0}..
        /// </summary>
        public static string MapZoomProperty_ZoomLevel_Description {
            get {
                return ResourceManager.GetString("MapZoomProperty_ZoomLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string OpenStreetMapTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("OpenStreetMapTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string SettingsGeoMapView_CommonSection_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_CommonSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit API Key.
        /// </summary>
        public static string SettingsGeoMapView_EditProviderApiKey_Tooltip {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_EditProviderApiKey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview point.
        /// </summary>
        public static string SettingsGeoMapView_MapPreview_Anchor {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MapPreview_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how the map looks with the current provider and zoom settings..
        /// </summary>
        public static string SettingsGeoMapView_MapPreview_Description {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MapPreview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map preview.
        /// </summary>
        public static string SettingsGeoMapView_MapPreview_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MapPreview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest zoom level available on the map..
        /// </summary>
        public static string SettingsGeoMapView_MaxZoomProperty_Description {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MaxZoomProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum zoom.
        /// </summary>
        public static string SettingsGeoMapView_MaxZoomProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MaxZoomProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest zoom level available on the map..
        /// </summary>
        public static string SettingsGeoMapView_MinZoomProperty_Description {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MinZoomProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum zoom.
        /// </summary>
        public static string SettingsGeoMapView_MinZoomProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_MinZoomProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether tiles are loaded from the network, local cache, or both..
        /// </summary>
        public static string SettingsGeoMapView_ModeProperty_Description {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_ModeProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map mode.
        /// </summary>
        public static string SettingsGeoMapView_ModeProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_ModeProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as current.
        /// </summary>
        public static string SettingsGeoMapView_SetCurrentProvider_Tooltip {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_SetCurrentProvider_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the tile source used to render the map..
        /// </summary>
        public static string SettingsGeoMapView_TileProviderProperty_Description {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_TileProviderProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map provider.
        /// </summary>
        public static string SettingsGeoMapView_TileProviderProperty_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_TileProviderProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string SettingsGeoMapView_ZoomSection_Title {
            get {
                return ResourceManager.GetString("SettingsGeoMapView_ZoomSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string SettingsGeoMapViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsGeoMapViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlas.
        /// </summary>
        public static string ThunderforestAtlasTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ThunderforestAtlasTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string ThunderforestCycleTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ThunderforestCycleTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string ThunderforestLandscapeTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ThunderforestLandscapeTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoors.
        /// </summary>
        public static string ThunderforestOutdoorsTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ThunderforestOutdoorsTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Dark.
        /// </summary>
        public static string ThunderforestTransportDarkTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ThunderforestTransportDarkTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string ThunderforestTransportTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("ThunderforestTransportTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS.
        /// </summary>
        public static string TileProviderGroup_ArcGis_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_ArcGis_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing.
        /// </summary>
        public static string TileProviderGroup_Bing_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Bing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string TileProviderGroup_Google_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Google_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERE.
        /// </summary>
        public static string TileProviderGroup_Here_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Here_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap.
        /// </summary>
        public static string TileProviderGroup_OpenStreetMap_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_OpenStreetMap_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string TileProviderGroup_Other_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Other_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderforest.
        /// </summary>
        public static string TileProviderGroup_Thunderforest_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Thunderforest_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yandex.
        /// </summary>
        public static string TileProviderGroup_Yandex_Name {
            get {
                return ResourceManager.GetString("TileProviderGroup_Yandex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} provider. Zoom levels {1}-{2}..
        /// </summary>
        public static string TileProviderViewModel_Description {
            get {
                return ResourceManager.GetString("TileProviderViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMP Poland.
        /// </summary>
        public static string UmpTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("UmpTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WikiMapia.
        /// </summary>
        public static string WikiMapiaTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("WikiMapiaTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string YandexSatelliteTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("YandexSatelliteTileProvider_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string YandexTileProvider_Info_Name {
            get {
                return ResourceManager.GetString("YandexTileProvider_Info_Name", resourceCulture);
            }
        }
    }
}
