//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude unit.
        /// </summary>
        public static string Altitude_Description {
            get {
                return ResourceManager.GetString("Altitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string Altitude_Name {
            get {
                return ResourceManager.GetString("Altitude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change unit sub type of the unit.
        /// </summary>
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change current unit item.
        /// </summary>
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application&apos;s language.
        /// </summary>
        public static string ChangeLanguageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application&apos;s theme.
        /// </summary>
        public static string ChangeThemeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string ChangeThemeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string DialogButton_DontSave {
            get {
                return ResourceManager.GetString("DialogButton_DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DialogButton_No {
            get {
                return ResourceManager.GetString("DialogButton_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DialogButton_Ok {
            get {
                return ResourceManager.GetString("DialogButton_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DialogButton_Save {
            get {
                return ResourceManager.GetString("DialogButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogButton_Yes {
            get {
                return ResourceManager.GetString("DialogButton_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance unit.
        /// </summary>
        public static string Distance_Description {
            get {
                return ResourceManager.GetString("Distance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance_Name {
            get {
                return ResourceManager.GetString("Distance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageVIewModel_Title {
            get {
                return ResourceManager.GetString("HomePageVIewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude in meters.
        /// </summary>
        public static string MeterAltitudeUnit_Description {
            get {
                return ResourceManager.GetString("MeterAltitudeUnit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string MeterAltitudeUnit_Name {
            get {
                return ResourceManager.GetString("MeterAltitudeUnit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string MeterAltitudeUnit_Symbol {
            get {
                return ResourceManager.GetString("MeterAltitudeUnit_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance in meters.
        /// </summary>
        public static string MeterDistanceUnit_Description {
            get {
                return ResourceManager.GetString("MeterDistanceUnit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string MeterDistanceUnit_Name {
            get {
                return ResourceManager.GetString("MeterDistanceUnit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string MeterDistanceUnit_Symbol {
            get {
                return ResourceManager.GetString("MeterDistanceUnit_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance in nautical miles.
        /// </summary>
        public static string NauticalMileDistanceUnit_Description {
            get {
                return ResourceManager.GetString("NauticalMileDistanceUnit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Mile.
        /// </summary>
        public static string NauticalMileDistanceUnit_Name {
            get {
                return ResourceManager.GetString("NauticalMileDistanceUnit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NM.
        /// </summary>
        public static string NauticalMileDistanceUnit_Symbol {
            get {
                return ResourceManager.GetString("NauticalMileDistanceUnit_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Debug Window.
        /// </summary>
        public static string OpenDebugCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Debug Window.
        /// </summary>
        public static string OpenDebugCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s language.
        /// </summary>
        public static string SettingsAppearanceView_AppLanguage_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s theme.
        /// </summary>
        public static string SettingsAppearanceView_AppTheme_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppTheme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string SettingsAppearanceView_HubHeader_CommonSettings {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_HubHeader_CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsAppearanceViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsAppearanceViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultHotKey.
        /// </summary>
        public static string SettingsKeyMapView_Header_DefaultHotKey {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_DefaultHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SettingsKeyMapView_Header_Description {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsKeyMapView_Header_Name {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SettingsKeymapViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsKeymapViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageViewModel_Title {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsUnitsView_Header_Default {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SettingsUnitsView_Header_Description {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsUnitsView_Header_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SettingsUnitsView_Header_Selected {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string SettingsUnitsViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ShellView_Toolbar_Edit {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ShellView_Toolbar_File {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ShellView_Toolbar_Help {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ShellView_Toolbar_View {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ShellView_WindowControlButton_Close {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeService_Dark {
            get {
                return ResourceManager.GetString("ThemeService_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeService_Light {
            get {
                return ResourceManager.GetString("ThemeService_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ThemeService_System {
            get {
                return ResourceManager.GetString("ThemeService_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last action.
        /// </summary>
        public static string UndoCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is empty.
        /// </summary>
        public static string UnitItemBase_Validation_ValueIsEmptyError {
            get {
                return ResourceManager.GetString("UnitItemBase_Validation_ValueIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a number.
        /// </summary>
        public static string UnitItemBase_Validation_ValueIsNaNError {
            get {
                return ResourceManager.GetString("UnitItemBase_Validation_ValueIsNaNError", resourceCulture);
            }
        }
    }
}
