//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string InstalledPluginsView_CancelUninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_CancelUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading error.
        /// </summary>
        public static string InstalledPluginsView_LoadingError {
            get {
                return ResourceManager.GetString("InstalledPluginsView_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string InstalledPluginsView_Search {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select plugin.
        /// </summary>
        public static string InstalledPluginsView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("InstalledPluginsView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string InstalledPluginsView_Tab_AdditionalInfo {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InstalledPluginsView_Tab_Description {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string InstalledPluginsView_Uninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        public static string InstalledPluginsView_Uninstalled {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin has been marked for deletion. It will be removed on the next application load..
        /// </summary>
        public static string InstalledPluginsView_UninstalledMessage {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        public static string InstalledPluginsView_UninstalledMessageTitle {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PluginInstallerViewModel_InstallDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string PluginInstallerViewModel_InstallDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Installer.
        /// </summary>
        public static string PluginInstallerViewModel_InstallDialog_Title {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin installed successfully.
        /// </summary>
        public static string PluginInstallerViewModel_InstallPluginAsync_Success {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallPluginAsync_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is verified by developers.
        /// </summary>
        public static string PluginsMarketView_InfoBar_IsVerified_Message {
            get {
                return ResourceManager.GetString("PluginsMarketView_InfoBar_IsVerified_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only verified.
        /// </summary>
        public static string PluginsMarketView_ToggleSwitch_OnlyVerified {
            get {
                return ResourceManager.GetString("PluginsMarketView_ToggleSwitch_OnlyVerified", resourceCulture);
            }
        }
    }
}
