//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.IO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.IO.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PortView_ButtonContent_Cancel {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PortView_ButtonContent_Save {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PortView_Switch_Off {
            get {
                return ResourceManager.GetString("PortView_Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PortView_Switch_On {
            get {
                return ResourceManager.GetString("PortView_Switch_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port name is required.
        /// </summary>
        public static string PortViewModel_ValidateName_Exception_PortNameRequired {
            get {
                return ResourceManager.GetString("PortViewModel_ValidateName_Exception_PortNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port name is too long. Max length is 50 characters.
        /// </summary>
        public static string PortViewModel_ValidateName_Exception_PortNameTooLong {
            get {
                return ResourceManager.GetString("PortViewModel_ValidateName_Exception_PortNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string SerialClientPortView_CommonSettings {
            get {
                return ResourceManager.GetString("SerialClientPortView_CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        public static string SerialPortView_Text_BaudRate {
            get {
                return ResourceManager.GetString("SerialPortView_Text_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SerialPortView_Text_Path {
            get {
                return ResourceManager.GetString("SerialPortView_Text_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SerialPortView_Text_Title {
            get {
                return ResourceManager.GetString("SerialPortView_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Serial port.
        /// </summary>
        public static string SettingsConnectionClientSerialExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionClientSerialExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TCP port.
        /// </summary>
        public static string SettingsConnectionTcpClientExtension_AddTcp_ButtonContent {
            get {
                return ResourceManager.GetString("SettingsConnectionTcpClientExtension_AddTcp_ButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string SettingsPageExtension_SettingsPageTitle_Connection {
            get {
                return ResourceManager.GetString("SettingsPageExtension_SettingsPageTitle_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string TcpClientPortView_Text_Host {
            get {
                return ResourceManager.GetString("TcpClientPortView_Text_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string TcpClientPortView_Text_Port {
            get {
                return ResourceManager.GetString("TcpClientPortView_Text_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TcpClientPortView_Text_Title {
            get {
                return ResourceManager.GetString("TcpClientPortView_Text_Title", resourceCulture);
            }
        }
    }
}
