//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.IO {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.IO.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SettingsConnectionTcpExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionTcpExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        public static string PortView_Title {
            get {
                return ResourceManager.GetString("PortView_Title", resourceCulture);
            }
        }
        
        public static string SettingsPageExtension_TreePage_Title {
            get {
                return ResourceManager.GetString("SettingsPageExtension_TreePage_Title", resourceCulture);
            }
        }
        
        public static string PortView_Text_PortNumber {
            get {
                return ResourceManager.GetString("PortView_Text_PortNumber", resourceCulture);
            }
        }
        
        public static string PortView_Text_Host {
            get {
                return ResourceManager.GetString("PortView_Text_Host", resourceCulture);
            }
        }
        
        public static string PortView_Text_Name {
            get {
                return ResourceManager.GetString("PortView_Text_Name", resourceCulture);
            }
        }
        
        public static string PortView_ButtonContent_Save {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Save", resourceCulture);
            }
        }
        
        public static string PortView_ButtonContent_Cancel {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Cancel", resourceCulture);
            }
        }
        
        public static string SerialPortView_Text_Name {
            get {
                return ResourceManager.GetString("SerialPortView_Text_Name", resourceCulture);
            }
        }
        
        public static string SerialPortView_TextPortName {
            get {
                return ResourceManager.GetString("SerialPortView_TextPortName", resourceCulture);
            }
        }
        
        public static string SerialPortView_Text_BaudRate {
            get {
                return ResourceManager.GetString("SerialPortView_Text_BaudRate", resourceCulture);
            }
        }
        
        public static string PortView_Switch_On {
            get {
                return ResourceManager.GetString("PortView_Switch_On", resourceCulture);
            }
        }
        
        public static string PortView_Switch_Off {
            get {
                return ResourceManager.GetString("PortView_Switch_Off", resourceCulture);
            }
        }
        
        public static string SettingsConnectionSerialExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionSerialExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        public static string TcpPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("TcpPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("SerialPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
        
        public static string PortCrudCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("PortCrudCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string PortCrudCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("PortCrudCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string HomePageDeviceItem_Description {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Description", resourceCulture);
            }
        }
        
        public static string HomePageDeviceItem_Info_Id {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Info_Id", resourceCulture);
            }
        }
        
        public static string HomePageDeviceItem_Info_Type {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Info_Type", resourceCulture);
            }
        }
        
        public static string HomePageDeviceItem_Info_Link {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Info_Link", resourceCulture);
            }
        }
        
        public static string UdpPortView_RemoteHost_On {
            get {
                return ResourceManager.GetString("UdpPortView_RemoteHost_On", resourceCulture);
            }
        }
        
        public static string UdpPortView_RemoteHost_Off {
            get {
                return ResourceManager.GetString("UdpPortView_RemoteHost_Off", resourceCulture);
            }
        }
        
        public static string UdpPortView_RemoteAddress {
            get {
                return ResourceManager.GetString("UdpPortView_RemoteAddress", resourceCulture);
            }
        }
        
        public static string UdpPortView_RemotePort {
            get {
                return ResourceManager.GetString("UdpPortView_RemotePort", resourceCulture);
            }
        }
        
        public static string UdpPortView_Connections_Header {
            get {
                return ResourceManager.GetString("UdpPortView_Connections_Header", resourceCulture);
            }
        }
        
        public static string SettingsConnectionView_Panel_NoConnections {
            get {
                return ResourceManager.GetString("SettingsConnectionView_Panel_NoConnections", resourceCulture);
            }
        }
        
        public static string SettingsConnectionView_Panel_Hint {
            get {
                return ResourceManager.GetString("SettingsConnectionView_Panel_Hint", resourceCulture);
            }
        }
        
        public static string SettingsConnectionView_SelectPort {
            get {
                return ResourceManager.GetString("SettingsConnectionView_SelectPort", resourceCulture);
            }
        }
        
        public static string ConnectionRateStatusView_NavigationButton_Settings {
            get {
                return ResourceManager.GetString("ConnectionRateStatusView_NavigationButton_Settings", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_TotalBytes_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_TotalBytes_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_ByteRate_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_ByteRate_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_TotalMessages_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_TotalMessages_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_MessagesRate_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_MessagesRate_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_Dropped_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_Dropped_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_Error_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_Error_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_BadCrc_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_BadCrc_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_ParsedBytes_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_ParsedBytes_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_ParsedMessages_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_ParsedMessages_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_MessageReadNotAllData_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_MessageReadNotAllData_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_DeserializeErrors_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_DeserializeErrors_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Row_UnknownMessages_Text {
            get {
                return ResourceManager.GetString("StatisticView_Row_UnknownMessages_Text", resourceCulture);
            }
        }
        
        public static string StatisticView_Table_ReceivedData_Title {
            get {
                return ResourceManager.GetString("StatisticView_Table_ReceivedData_Title", resourceCulture);
            }
        }
        
        public static string StatisticView_Table_TransmittedData_Title {
            get {
                return ResourceManager.GetString("StatisticView_Table_TransmittedData_Title", resourceCulture);
            }
        }
        
        public static string StatisticView_Table_Protocols_Title {
            get {
                return ResourceManager.GetString("StatisticView_Table_Protocols_Title", resourceCulture);
            }
        }
        
        public static string SerialPortView_Text_Driver {
            get {
                return ResourceManager.GetString("SerialPortView_Text_Driver", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_ValidationException_BaudRateIsNull {
            get {
                return ResourceManager.GetString("SerialPortViewModel_ValidationException_BaudRateIsNull", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_ValidationException_BaudRateNaN {
            get {
                return ResourceManager.GetString("SerialPortViewModel_ValidationException_BaudRateNaN", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_ValidationException_BaudRateNegative {
            get {
                return ResourceManager.GetString("SerialPortViewModel_ValidationException_BaudRateNegative", resourceCulture);
            }
        }
        
        public static string SerialPortView_ToggleSwitch_Version2 {
            get {
                return ResourceManager.GetString("SerialPortView_ToggleSwitch_Version2", resourceCulture);
            }
        }
        
        public static string SerialPortView_ToggleSwitch_Version1 {
            get {
                return ResourceManager.GetString("SerialPortView_ToggleSwitch_Version1", resourceCulture);
            }
        }
        
        public static string SettingsConnectionSerialPortExtension_DefaultConfig_Name {
            get {
                return ResourceManager.GetString("SettingsConnectionSerialPortExtension_DefaultConfig_Name", resourceCulture);
            }
        }
        
        public static string SettingsConnectionTcpPortExtension_DefaultConfig_Name {
            get {
                return ResourceManager.GetString("SettingsConnectionTcpPortExtension_DefaultConfig_Name", resourceCulture);
            }
        }
        
        public static string SettingsConnectionTcpServerPortExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionTcpServerPortExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        public static string SettingsConnectionTcpServerPortExtension_DefaultConfig_Name {
            get {
                return ResourceManager.GetString("SettingsConnectionTcpServerPortExtension_DefaultConfig_Name", resourceCulture);
            }
        }
        
        public static string TcpServerEndpointViewModel_Header {
            get {
                return ResourceManager.GetString("TcpServerEndpointViewModel_Header", resourceCulture);
            }
        }
        
        public static string TcpServerPortView_Connections_Header {
            get {
                return ResourceManager.GetString("TcpServerPortView_Connections_Header", resourceCulture);
            }
        }
        
        public static string UdpEndpointViewModel_Header {
            get {
                return ResourceManager.GetString("UdpEndpointViewModel_Header", resourceCulture);
            }
        }
        
        public static string TcpServerPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("TcpServerPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
        
        public static string SettingsConnectionUdpPortExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionUdpPortExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        public static string SettingsConnectionUdpPortExtension_DefaultConfig_Name {
            get {
                return ResourceManager.GetString("SettingsConnectionUdpPortExtension_DefaultConfig_Name", resourceCulture);
            }
        }
        
        public static string UdpPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("UdpPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
        
        public static string PortViewModel_StatusMessage_Disabled {
            get {
                return ResourceManager.GetString("PortViewModel_StatusMessage_Disabled", resourceCulture);
            }
        }
        
        public static string PortViewModel_ProtocolPortStatus_Connected {
            get {
                return ResourceManager.GetString("PortViewModel_ProtocolPortStatus_Connected", resourceCulture);
            }
        }
        
        public static string PortViewModel_ProtocolPortStatus_InProgress {
            get {
                return ResourceManager.GetString("PortViewModel_ProtocolPortStatus_InProgress", resourceCulture);
            }
        }
        
        public static string PortViewModel_ProtocolPortStatus_Disconected {
            get {
                return ResourceManager.GetString("PortViewModel_ProtocolPortStatus_Disconected", resourceCulture);
            }
        }
        
        public static string PortViewModel_ProtocolPortStatus_Error {
            get {
                return ResourceManager.GetString("PortViewModel_ProtocolPortStatus_Error", resourceCulture);
            }
        }
        
        public static string PortViewModel_ValidationException_IsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("PortViewModel_ValidationException_IsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        public static string PortViewModel_ValidationException_TooLong {
            get {
                return ResourceManager.GetString("PortViewModel_ValidationException_TooLong", resourceCulture);
            }
        }
    }
}
