//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Example {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.Example.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls gallery.
        /// </summary>
        public static string ControlsGalleryPageViewModel_Title {
            get {
                return ResourceManager.GetString("ControlsGalleryPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary / Secondary:.
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_Buttons {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_Content {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new dialog from scratch. You can configure its content, the displayed buttons, their text, and whether they are enabled or not. Below you will find only a few customization options — all other parameters are configured programmatically..
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom dialog.
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_Header {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_ImageContent {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_ImageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo....
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_ImageContent_Select {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_ImageContent_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open dialog.
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_Open {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_TextContent {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_TextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string DialogControlsPageView_ContentDialog_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom dialog prefabs.
        /// </summary>
        public static string DialogControlsPageView_Custom_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of dialogs — windows for text input, option selection, action confirmation and so on..
        /// </summary>
        public static string DialogControlsPageView_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allows the user to select a point on the map.
        ///
        ///• Input: initial location.  
        ///• Output: GeoPoint.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_GeoPointPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_GeoPointPrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open geopoint dialog.
        /// </summary>
        public static string DialogControlsPageView_GeoPointPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_GeoPointPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allows the user to choose a hotkey by pressing it.
        ///
        ///• Input: title, message, and default hotkey.  
        ///• Output: selected hotkey.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_HotKeyCapturePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_HotKeyCapturePrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open key capture dialog.
        /// </summary>
        public static string DialogControlsPageView_HotKeyCapturePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_HotKeyCapturePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allows the user to enter text.
        ///
        ///• Input: dialog title and message.  
        ///• Output: entered text value.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_InputPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_InputPrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some text....
        /// </summary>
        public static string DialogControlsPageView_InputPrefab_Placeholder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_InputPrefab_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open input dialog.
        /// </summary>
        public static string DialogControlsPageView_InputPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_InputPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Shows the contents of the selected folder.
        ///
        ///• Input: dialog title and default path.  
        ///• Output: none.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_ObserveFolderPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ObserveFolderPrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button....
        /// </summary>
        public static string DialogControlsPageView_ObserveFolderPrefab_PlaceHolder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ObserveFolderPrefab_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observe folder.
        /// </summary>
        public static string DialogControlsPageView_ObserveFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ObserveFolderPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allows the user to open a file.
        ///
        ///• Input: title, type filter, and initial directory.  
        ///• Output: selected file path.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_OpenFilePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_OpenFilePrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string DialogControlsPageView_OpenFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_OpenFilePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use ready-made dialog prefabs that are suitable for most tasks, such as text input, selecting a geolocation point, choosing a file, and so on. Some parameters in them, such as the message or button availability, can also be customized. Prefabs are divided into two types: custom dialogs created manually for specific tasks, and system dialogs such as the file picker..
        /// </summary>
        public static string DialogControlsPageView_Prefabs_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Prefabs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready dialog prefabs.
        /// </summary>
        public static string DialogControlsPageView_Prefabs_Header {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Prefabs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allows the user to save a file.
        ///
        ///• Input: title, default extension, type filter, and initial directory.  
        ///• Output: selected file path.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_SaveFilePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SaveFilePrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string DialogControlsPageView_SaveFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SaveFilePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Used to confirm saving information.
        ///
        ///• Input: dialog title and message.  
        ///• Output: true or false.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_SavePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SavePrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open saving dialog.
        /// </summary>
        public static string DialogControlsPageView_SavePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SavePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allows the user to select a folder.
        ///
        ///• Input: dialog title and initial location.  
        ///• Output: selected folder path.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_SelectFolderPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SelectFolderPrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string DialogControlsPageView_SelectFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SelectFolderPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System dialogs are available on desktop platforms. Some options depend on OS capabilities..
        /// </summary>
        public static string DialogControlsPageView_System_Note {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefabs of the system dialogs.
        /// </summary>
        public static string DialogControlsPageView_System_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allows the user to agree or decline.
        ///
        ///• Input: dialog title and message.  
        ///• Output: true or false.
        ///    .
        /// </summary>
        public static string DialogControlsPageView_YesOrNoPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_YesOrNoPrefab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open confirmation dialog.
        /// </summary>
        public static string DialogControlsPageView_YesOrNoPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_YesOrNoPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DialogControlsPageViewModel_CancelResult {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_CancelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DialogControlsPageViewModel_ContentDialog_Close {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string DialogControlsPageViewModel_ContentDialog_Primary {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom dialog result: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_ContentDialog_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string DialogControlsPageViewModel_ContentDialog_Secondary {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected GeoPoint: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_GeoPointPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_GeoPointPrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key.
        /// </summary>
        public static string DialogControlsPageViewModel_HotKeyCapturePrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapturePrefab_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected HotKey: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_HotKeyCapturePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapturePrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Capture.
        /// </summary>
        public static string DialogControlsPageViewModel_HotKeyCapturePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapturePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the data.
        /// </summary>
        public static string DialogControlsPageViewModel_InputPrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_InputPrefab_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_InputPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_InputPrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string DialogControlsPageViewModel_InputPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_InputPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed folder: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_ObserveFolderPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolderPrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory opened!.
        /// </summary>
        public static string DialogControlsPageViewModel_ObserveFolderPrefab_ResultShort {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolderPrefab_ResultShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observe Folder.
        /// </summary>
        public static string DialogControlsPageViewModel_ObserveFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolderPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened file: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_OpenFilePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFilePrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string DialogControlsPageViewModel_OpenFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFilePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved file: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_SaveFilePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFilePrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string DialogControlsPageViewModel_SaveFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFilePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        public static string DialogControlsPageViewModel_SavePrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SavePrefab_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_SavePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SavePrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string DialogControlsPageViewModel_SavePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SavePrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_SelectFolderPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolderPrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string DialogControlsPageViewModel_SelectFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolderPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        public static string DialogControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit?.
        /// </summary>
        public static string DialogControlsPageViewModel_YesOrNoPrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNoPrefab_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_YesOrNoPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNoPrefab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogControlsPageViewModel_YesOrNoPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNoPrefab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string HistoricalControlsPageView_Basic {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of historical properties with simple editing..
        /// </summary>
        public static string HistoricalControlsPageView_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum:.
        /// </summary>
        public static string HistoricalControlsPageView_Enum {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoPoint:.
        /// </summary>
        public static string HistoricalControlsPageView_GeoPoint {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_GeoPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules: non-empty; and second input additionally forbids ‘s’..
        /// </summary>
        public static string HistoricalControlsPageView_Rules_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many rules:.
        /// </summary>
        public static string HistoricalControlsPageView_Rules_Many {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One rule:.
        /// </summary>
        public static string HistoricalControlsPageView_Rules_One {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String (no validation):.
        /// </summary>
        public static string HistoricalControlsPageView_String {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle:.
        /// </summary>
        public static string HistoricalControlsPageView_Toggle {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string HistoricalControlsPageView_Unit {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string HistoricalControlsPageView_Validation {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value shouldn&apos;t contain &apos;s&apos;.
        /// </summary>
        public static string HistoricalControlsPageViewModel_StringPropWithManyValidations_ValidationError_ShouldNotContainS {
            get {
                return ResourceManager.GetString(("HistoricalControlsPageViewModel_StringPropWithManyValidations_ValidationError_Sho" +
                        "uldNotContainS"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical fields.
        /// </summary>
        public static string HistoricalControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("HistoricalControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With action button.
        /// </summary>
        public static string InfoBoxControlsPageView_ActionButton {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do action.
        /// </summary>
        public static string InfoBoxControlsPageView_ActionButton_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string InfoBoxControlsPageView_Basic {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closable.
        /// </summary>
        public static string InfoBoxControlsPageView_Closable {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Closable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string InfoBoxControlsPageView_Common_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string InfoBoxControlsPageView_Common_Severity {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string InfoBoxControlsPageView_Common_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline notification for app-wide messages. Examples below show basic usage, action button, and closable variants..
        /// </summary>
        public static string InfoBoxControlsPageView_Description {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string InfoBoxControlsPageView_Examples {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example InfoBox message.
        /// </summary>
        public static string InfoBoxControlsPageViewModel_Example_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example InfoBox title.
        /// </summary>
        public static string InfoBoxControlsPageViewModel_Example_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoBox.
        /// </summary>
        public static string InfoBoxControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Example.
        /// </summary>
        public static string MapControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("MapControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that open&apos;s controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the geopoint dialog result.
        /// </summary>
        public static string ResetGeoPointDialogResultCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ResetGeoPointDialogResultCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset geopoint dialog.
        /// </summary>
        public static string ResetGeoPointDialogResultCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ResetGeoPointDialogResultCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string ShellLeftMenuExtenderExample_HomeItem_Header {
            get {
                return ResourceManager.GetString("ShellLeftMenuExtenderExample_HomeItem_Header", resourceCulture);
            }
        }
    }
}
