//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Example {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.Example.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DialogControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string MapControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("MapControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("HistoricalControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string ControlsGalleryPageViewModel_Title {
            get {
                return ResourceManager.GetString("ControlsGalleryPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_OpenFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFilePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SaveFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFilePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SelectFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolderPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ObserveFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolderPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_YesOrNoPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNoPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_YesOrNoPrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNoPrefab_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SavePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SavePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SavePrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SavePrefab_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_HotKeyCapturePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapturePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_HotKeyCapturePrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapturePrefab_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_InputPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_InputPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_InputPrefab_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_InputPrefab_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_Note {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Note", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Description", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Description {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Title", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Rules_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Description", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Rules_One {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_One", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Rules_Many {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Many", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Common_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Title", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Common_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Message", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Common_Severity {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Severity", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Basic {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Basic", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_ActionButton {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Closable {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Closable", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Examples {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Examples", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_ActionButton_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton_Title", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_GeoPoint {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_GeoPoint", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Toggle {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Toggle", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_String {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_String", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Unit {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Unit", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Basic {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Basic", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Validation {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Validation", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageViewModel_Example_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Title", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageViewModel_Example_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_OpenFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_OpenFilePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_SaveFilePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SaveFilePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_SelectFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SelectFolderPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ObserveFolderPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ObserveFolderPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_YesOrNoPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_YesOrNoPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_SavePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SavePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_InputPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_InputPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_HotKeyCapturePrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_HotKeyCapturePrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_CancelResult {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_CancelResult", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_OpenFilePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFilePrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SaveFilePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFilePrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SelectFolderPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolderPrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ObserveFolderPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolderPrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_YesOrNoPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNoPrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SavePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SavePrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_InputPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_InputPrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_HotKeyCapturePrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapturePrefab_Result", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Title", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Description", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Enum {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Enum", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_GeoPointPrefab_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_GeoPointPrefab_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_GeoPointPrefab_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_GeoPointPrefab_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_Content {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Content", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_Buttons {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Buttons", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_Header {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Header", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Prefabs_Header {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Prefabs_Header", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Prefabs_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Prefabs_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_SelectFolderPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SelectFolderPrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_SaveFilePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SaveFilePrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_OpenFilePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_OpenFilePrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ObserveFolderPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ObserveFolderPrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_YesOrNoPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_YesOrNoPrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_HotKeyCapturePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_HotKeyCapturePrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_GeoPointPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_GeoPointPrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_InputPrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_InputPrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_SavePrefab_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_SavePrefab_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ContentDialog_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ObserveFolderPrefab_ResultShort {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolderPrefab_ResultShort", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ContentDialog_Primary {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Primary", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ContentDialog_Secondary {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Secondary", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ContentDialog_Close {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ContentDialog_Close", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_InputPrefab_Placeholder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_InputPrefab_Placeholder", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_TextContent {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_TextContent", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_ImageContent {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_ImageContent", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_ImageContent_Select {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_ImageContent_Select", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ObserveFolderPrefab_PlaceHolder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ObserveFolderPrefab_PlaceHolder", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_ContentDialog_Open {
            get {
                return ResourceManager.GetString("DialogControlsPageView_ContentDialog_Open", resourceCulture);
            }
        }
        
        public static string ResetGeoPointDialogResultCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ResetGeoPointDialogResultCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ResetGeoPointDialogResultCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ResetGeoPointDialogResultCommand_CommandInfo_Description", resourceCulture);
            }
        }
    }
}
